import fs from 'node:fs';
import assert from 'node:assert/strict';
for (const lang of ['ko','en']) {
  const source=fs.readFileSync(new URL(`../custom_components/carrot_ha/frontend/carrot-dashboard-${lang}.js`,import.meta.url),'utf8');
  const body=source.match(/vehicleStatus\(v\)\{([\s\S]*?)\n  \}/)[1];
  const context={_hass:{states:{online:{state:'on'}}},config:{online_entity:'online'}};
  const state=new Function('v',body).bind(context);
  assert.equal(state({onroad:true,driving:false,charging:true}).key,'charging');
  assert.equal(state({onroad:true,driving:false,charging:true}).label,lang==='ko'?'충전중':'Charging');
  assert.equal(state({onroad:true,charging:true}).key,'charging');
  assert.equal(state({onroad:true,charging:true}).label,lang==='ko'?'충전중':'Charging');
  assert.equal(state({onroad:true,driving:null,charging:null}).key,'unknown');
  assert.equal(state({onroad:true,driving:true,charging:false}).key,'driving');
  assert.equal(state({onroad:true}).key,'driving');
  assert.equal(state({driving:false,charging:true,stale:true}).key,'charging');
  assert.equal(state({driving:false,charging:true,measured_at:new Date(Date.now()-240000).toISOString()}).key,'charging');
  const stamp=new Date(Date.now()-600000).toISOString();
  const parked=state({driving:false,charging:null,stale:true,measured_at:stamp});
  assert.equal(parked.key,'parked');
  assert.equal(parked.label,lang==='ko'?'주차중':'Parked');
  assert.equal(state({driving:false,charging:true,stale:true,measured_at:stamp}).key,'charging');
  assert.equal(state({driving:false,charging:true,stale:true,measured_at:stamp}).label,lang==='ko'?'충전중':'Charging');
  assert.equal(state({driving:true,stale:true}).key,'driving');
  assert.equal(state({driving:true,stale:true}).label,lang==='ko'?'주행 중':'Driving');
  assert.equal(state({driving:null,stale:true}).key,'unknown');
  assert.equal(state({driving:null,stale:true}).label,lang==='ko'?'상태 확인 중':'Checking status');
  assert.equal(state({driving:false,charging:true,measured_at:new Date().toISOString()}).key,'charging');
  context._hass.states.online.state='off';
  assert.equal(state({driving:false,charging:true,stale:true}).key,'offline');
  assert.equal(state({driving:false,charging:true,stale:true}).label,lang==='ko'?'오프라인':'Offline');
  context._hass.states.online.state='unavailable';
  assert.equal(state({driving:false}).key,'unknown');
  assert.equal(state({driving:false}).label,lang==='ko'?'연결 확인 중':'Checking connection');
}
console.log('PASS: motion classification and simplified vehicleStatus in both languages');
