import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from './src/worker.js';
const db = new DatabaseSync(':memory:');
db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));
let queries=[];
const env={SNAPSHOTS:{},WAYON_UPLOAD_TOKEN:'upload',WAYON_VIEW_TOKEN:'view',DB:{prepare(sql){
  queries.push(sql);let args=[];const statement=db.prepare(sql);
  return {bind(...values){args=values;return this;},async first(){return statement.get(...args)??null;},async all(){return {results:statement.all(...args)};},async run(){return statement.run(...args);}};
}}};
const call=async(path,body,token=body?'upload':'view')=>{
  const response=await worker.fetch(new Request('https://example.test'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),env,{});
  return {status:response.status,body:await response.json()};
};
const trip=(id,device='car')=>({id,deviceId:device,startedAt:'2026-10-01T01:00:00Z',endedAt:'2026-10-01T01:10:00Z',durationS:600,distanceM:1000,partial:false,route:[{latitude:37,longitude:127,speedMps:10}]});
assert.equal((await call('/api/trip-changes?device_id=car',null,'bad')).status,401);
assert.equal((await call('/api/trip-changes?device_id=car&after=-1')).status,400);
await call('/api/trips',trip('one'));await call('/api/trips',trip('other','other'));
queries=[];
let feed=await call('/api/trip-changes?device_id=car');
assert.equal(feed.status,200);assert.equal(queries.length,1);
assert.deepEqual(feed.body.trips.map(t=>t.id),['one']);
assert.equal(feed.body.trips[0].route.length,1);assert.equal(feed.body.trips[0].partial,false);
let cursor=feed.body.next_cursor;
const changes=after=>call(`/api/trip-changes?device_id=car&after=${after}&limit=1`);
assert.equal((await changes(cursor)).body.trips.length,0);
await call('/api/trips',trip('one'));
assert.equal((await changes(cursor)).body.trips.length,0,'identical retry must not create a revision');
await call('/api/trips',{...trip('one'),distanceM:1200,route:[{latitude:38,longitude:128}]});
feed=await changes(cursor);assert.equal(feed.body.trips[0].distance_m,1200);assert.equal(feed.body.trips[0].route[0].latitude,38);
cursor=feed.body.next_cursor;
db.prepare('UPDATE trip_quality SET partial=1 WHERE id=?').run('one');
feed=await changes(cursor);assert.equal(feed.body.trips[0].partial,true);cursor=feed.body.next_cursor;
db.prepare('INSERT INTO trip_distance_quality VALUES(?,?,?)').run('one','can_speed','{"complete":true}');
feed=await changes(cursor);assert.equal(feed.body.trips[0].distance_quality.complete,true);cursor=feed.body.next_cursor;
db.prepare('DELETE FROM trip_distance_quality WHERE id=?').run('one');
feed=await changes(cursor);assert.equal(feed.body.trips[0].distance_source,null);cursor=feed.body.next_cursor;
await call('/api/trips',trip('two'));await call('/api/trips',trip('three'));
feed=await changes(cursor);assert.equal(feed.body.has_more,true);cursor=feed.body.next_cursor;
feed=await changes(cursor);assert.equal(feed.body.trips[0].id,'three');assert.equal(feed.body.has_more,false);cursor=feed.body.next_cursor;
db.exec("DELETE FROM trips WHERE device_id='car'");
await call('/api/trips',trip('four'));
feed=await changes(cursor);assert.equal(feed.body.trips[0].id,'four','purge cannot reuse cursor');
const seq=feed.body.next_cursor;
db.exec(readFileSync(new URL('./migration_incremental_sync.sql',import.meta.url),'utf8'));
assert.equal((await changes(seq)).body.trips.length,0,'rerunning migration preserves existing cursors');
// Query plan must seek the device/revision index, not scan all history.
const plan=db.prepare('EXPLAIN QUERY PLAN SELECT * FROM trip_sync_revision WHERE device_id=? AND sequence>? ORDER BY sequence LIMIT ?').all('car',seq,11);
assert.ok(plan.some(row=>/SEARCH.*trip_sync_device_sequence/.test(row.detail)));
env.WAYON_SERVER_API={};env.WAYON_SERVER_SYNC_TOKEN='server';
assert.equal((await changes(seq)).status,409);
delete env.WAYON_SERVER_API;delete env.WAYON_SERVER_SYNC_TOKEN;
// Settings presence + conditional snapshots + polling hints, scoped by device.
await call('/api/settings/sync',{device_id:'car',catalog:{params:[{name:'Test',min:0,max:10}]},values:{Test:2}});
const settings=await call('/api/settings?device_id=car&active=1');assert.equal(settings.body.ok,true);
assert.equal((await call('/api/params/pending?device_id=car',null,'upload')).body.poll_after_s,3);
assert.equal((await call('/api/params/pending?device_id=other',null,'upload')).body.poll_after_s,15);
queries=[];
const same=await call('/api/settings?device_id=car&active=1&known='+encodeURIComponent(settings.body.updated_at));
assert.equal(same.body.unchanged,true);assert.ok(!('catalog' in same.body));
assert.ok(!queries.some(sql=>sql.includes('catalog_json')));
db.exec("UPDATE param_activity SET active_until=0 WHERE device_id='car'");
assert.equal((await call('/api/params/pending?device_id=car',null,'upload')).body.poll_after_s,15);
console.log('PASS incremental mutations, replay, isolation, cursor/purge/migration, indexed query and adaptive settings');
const queue=await call('/api/params/queue',{device_id:'car',param_name:'Test',param_value:4},'view');
const pending=await call('/api/params/pending?device_id=car',null,'upload');
const failedId=pending.body.pending[0].id;
assert.equal(pending.body.poll_after_s,3);
await call('/api/params/ack',{device_id:'car',applied_ids:[],failed_ids:[failedId]});
assert.equal((await call(`/api/params/status?device_id=car&ids=${failedId}`)).body.queue[0].status,'failed');
await call('/api/params/ack',{device_id:'car',applied_ids:[failedId]});
assert.equal((await call(`/api/params/status?device_id=car&ids=${failedId}`)).body.queue[0].status,'failed','late ACK must not turn rejected commands into applied');
assert.equal((await call('/api/params/ack',{device_id:'car',applied_ids:['bad']})).status,400);
assert.equal((await call('/api/params/pending?device_id=car',null,'upload')).body.pending.length,0);
console.log('PASS rejection ACK drains queue and terminal statuses cannot be overwritten');
